name: Build Android APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Pegar o código
      - name: Checkout repository
        uses: actions/checkout@v4

      # Passo 2: Configurar JDK
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Passo 3: Cache do Gradle (opcional, acelera builds)
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Passo 4: Build do APK
      - name: Build APK
        run: ./gradlew assembleRelease

      # Passo 5: Upload do APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: app/build/outputs/apk/release/app-release.apk


